### ISSUE TITLE
Stopped working with latest snapshot versions

### ISSUE THREAD

**Issue by aiba** [philjackson/cljr-helm#5]
After some updates, cljr-helm stopped working.  I really miss it.

When I run `M-x cljr-helm`, I just a helm completion buffer pops up but it is empty.

Here are the versions of my packages.  Emacs was installed from brew, the other packages were installed from melpa.org.
- Emacs version: `GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47) of 2016-08-30`
- cljr version: `clj-refactor 2.3.0-SNAPSHOT (package: 20160621.902), refactor-nrepl 2.3.0-SNAPSHOT`
- helm version: `20160909.111`
- helm-core version: `20160908.25`
- cljr-helm version: `20150425.1307`

Any ideas what could be causing this?

**Comment by philjackson** [comment]
I've fixed in this repo and tagged it as 0.9. I can't for the life of me remember how I release an update to Melpa. Perhaps tagging is enough for some batch job to pick it up later - I'll keep an eye on it.

**Comment by aiba** [comment]
Worked like a charm, thank you!  melpa seemed to have picked up the new version, too.
